import PDFDocument from 'pdfkit';

export function buildContributionReport(

  group: any,

  contributions: any[],

): PDFKit.PDFDocument {

  const doc = new PDFDocument({

    margin: 50,

    size: 'A4',

  });

  /*
  ============================================================================
  Header
  ============================================================================
  */

  doc
    .fontSize(22)
    
    .text(

      group.name,

      {

        align: 'center',

      },

    );

    if (group.logo_url) {

        try {
      
          doc.image(
      
            group.logo_url,
      
            240,
      
            30,
      
            {
      
              width: 70,
      
            },
      
          );
      
          doc.moveDown(4);
      
        } catch {
      
          /**
           * Ignore invalid image
           */
      
        }
      
      }

  if (group.location) {

    doc
      .moveDown(0.3)
      .fontSize(11)
      .text(

        group.location,

        {

          align: 'center',

        },

      );

  }

  doc
    .moveDown()

    .fontSize(16)

    .text(

      'Contribution Report',

      {

        align: 'center',

      },

    );

  doc
    .moveDown(0.5)

    .fontSize(10)

    .text(

      `Generated: ${new Date().toLocaleString()}`,

      {

        align: 'right',

      },

    );

  doc.moveDown(2);

  /*
  ============================================================================
  Table Header
  ============================================================================
  */

  doc.font('Helvetica-Bold');

  doc.text(

    'Member',

    50,

    doc.y,

  );

  doc.text(

    'Type',

    170,

    doc.y - 15,

  );

  doc.text(

    'Amount',

    300,

    doc.y - 15,

  );

  doc.text(

    'Status',

    390,

    doc.y - 15,

  );

  doc.text(

    'Date',

    470,

    doc.y - 15,

  );

  doc.moveDown();

  doc.font('Helvetica');

  /*
  ============================================================================
  Rows
  ============================================================================
  */

  let total = 0;

  contributions.forEach(

    (item) => {

      total += item.amount;

      doc.text(

        item.member,

        50,

        doc.y,

      );

      doc.text(

        item.contributionType,

        170,

        doc.y - 15,

      );

      doc.text(

        `${group.currency} ${item.amount}`,

        300,

        doc.y - 15,

      );

      doc.text(

        item.status,

        390,

        doc.y - 15,

      );

      doc.text(

        new Date(

          item.paymentDate,

        ).toLocaleDateString(),

        470,

        doc.y - 15,

      );

      doc.moveDown();

    },

  );

  /*
  ============================================================================
  Totals
  ============================================================================
  */

  doc.moveDown(2);

  doc.font('Helvetica-Bold');

  doc.text(

    `TOTAL CONTRIBUTIONS : ${group.currency} ${total.toLocaleString()}`,

    {

      align: 'right',

    },

  );

  /*
  ============================================================================
  Footer
  ============================================================================
  */

  doc.moveDown(3);

  doc.fontSize(9);

  doc.text(

    'Generated by Pamoja Chama',

    {

      align: 'center',

    },

  );

  doc.end();

  return doc;

}